### ISSUE TITLE
create API documentation 

### ISSUE THREAD

**Issue by championswimmer** [coding-blocks/hiring-blocks#1]

**Comment by bhavyaagg** [comment]
@championswimmer Solved this. Please close this issue.

**Comment by championswimmer** [comment]
cool. claim the bounty. use https://github.com/coding-blocks/hiring-blocks/commit/dd6a12051355ff3360584e72a1cff385af9d8693 as PR url

**Comment by bhavyaagg** [comment]
@championswimmer bhaiya i can not claim the bounty using commit id as the PR url because the in the backend code, To create a claim you use :
repo: pullUrl.split('github.com/')[1].split('/')[1]
So it shows an error.
