### ISSUE TITLE
configure for deploying to heroku

### ISSUE THREAD

**Issue by championswimmer** [coding-blocks/hiring-blocks#24]
- [x] create app.json
- [x] use the postgres plugin (heroku supports postgres) in app.json
- [x] generate secrets.json appropriately
- [x] test and see it works on heroku

**Comment by ananay** [comment]
Here you go!
https://github.com/coding-blocks/hiring-blocks/pull/26

**Comment by bhavyaagg** [comment]
Check #25 too.
